### PR TITLE
Use fs.accessSync instead of fs.realpathSync and catch exceptions (fixes #49)

### LINKED ISSUE #49: 0.1.11 Breaks Chrome launching on OS X
Looks like this was introduced by d442548e3ca91bb200ddeca9d1384155bc499056

From what I can tell `fs.realpathSync` throws an error if the path isn't found, but the code expects it to return true/false.  The error prevents the `defaultPath` param from getting registered and Chrome doesn't launch.

```
WARN [plugin]: Error during loading "/Users/joechrz/projects/fire-engine/node_modules/karma-chrome-launcher" plugin:
  ENOENT, no such file or directory '/Users/joechrz/Applications/Google Chrome.app'
INFO [framework.browserify]: registering rebuild (autoWatch=true)
[17:10:37] Starting 'serve'...
fire-engine.js was browserified: 0.701s
WARN [karma]: Port 9876 in use
[17:10:37] Finished 'serve' after 1.5 ms
INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
WARN [launcher]: Can not load "Chrome", it is not registered!
  Perhaps you are missing some plugin?
```

### PR DESCRIPTION
**Pull request by alias-mac**
Both `fs.accessSync` and `fs.realpathSync` throw exceptions that need be
caught. There is no requirement to use `realpath`, since we don't use relative
paths.

### CODE REVIEW

**Comment by alias-mac** [comment]
Caused by #42 and dupe of #49

File: index.js [hunk 1]
```diff
@@ -54,10 +54,11 @@ function getChromeExe(chromeDirName) {
 
   for (i = 0; i < prefixes.length; i++) {
     prefix = prefixes[i];
-    if (fs.realpathSync(prefix + suffix)) {
-      windowsChromeDirectory = prefix + suffix;
-      break;
-    }
+    try {
+      windowsChromeDirectory = path.join(prefix, suffix);
+      fs.accessSync(windowsChromeDirectory);
```
Comment (alias-mac) [inline index.js]: `fs.F_OK` is the default mode for `accessSync`, which is what we need to check if the file (Windows) folder (OS X) exists https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback

**Comment by mzgol** [comment]
This fixes the issue for me, I tested locally. :+1: `

**Comment by alias-mac** [comment]
Thanks for checking @mzgol!

**Comment by zzo** [comment]
published  to npm  v0.1.12

**Comment by mzgol** [comment]
Thanks! The new version works fine for me.

**Comment by mponizil** [comment]
Works for me too. Thanks!
